from itsdangerous import URLSafeTimedSerializer

# https://www.freecodecamp.org/news/setup-email-verification-in-flask-app/


def generate_token(charid, app):
    """Generates a confirmation token to be inserted into the chosen character's lodestone character profile """
    serialiser = URLSafeTimedSerializer(app.config["SECRET_KEY"])
    return serialiser.dumps(charid, salt=app.config["SECURITY_PASSWORD_SALT"])


def generate_account_token(email, app):
    """Generates a confirmation token for email account verification"""
    serialiser = URLSafeTimedSerializer(app.config["SECRET_KEY"])
    return serialiser.dumps(email, app.config["SECURITY_PASSWORD_SALT"])


def generate_password_token(charid, email, app):
    """Generates a token used for password resets containing the charid and email of a character"""
    serialiser = URLSafeTimedSerializer(app.config["SECRET_KEY"])
    # Space seperated, split when decoding
    return serialiser.dumps(f"{charid} {email}", salt=app.config["SECURITY_PASSWORD_SALT"])


def confirm_token(token, app, expiration=3600) -> str:
    """Decodes a token generated by generate_token, returns an empty string if any exception is encountered (due to token expiry, malformed token, etc)"""
    serialiser = URLSafeTimedSerializer(app.config["SECRET_KEY"])
    try:
        charid = serialiser.loads(
            token,
            salt=app.config["SECURITY_PASSWORD_SALT"],
            max_age=expiration,
        )
        return charid
    except Exception:
        return ""


def confirm_account_token(token, app, expiration=1800) -> str:
    """Decodes a token generated by generate_account_token, returns an empty string if any exception is encountered (due to token expiry, malformed token, etc)"""
    serialiser = URLSafeTimedSerializer(app.config["SECRET_KEY"])
    try:
        email = serialiser.loads(
            token,
            salt=app.config["SECURITY_PASSWORD_SALT"],
            max_age=expiration,
        )

        return email
    except Exception:
        return ""


def confirm_password_token(token, app, expiration=300) -> list[str]:
    """Decodes a token generated by generate_password_token, returns an empty string if any exception is encountered (due to token expiry, malformed token, etc)"""
    serialiser = URLSafeTimedSerializer(app.config["SECRET_KEY"])
    try:
        chars = serialiser.loads(
            token,
            salt=app.config["SECURITY_PASSWORD_SALT"],
            max_age=expiration
        )
        return chars.split(" ")
    except Exception:
        return ""
